- name: Server setup
  hosts: gateway
  become: true
  vars:
    headscale_users:
      - matthew
      - restricted
      # TODO: Look into tagged devices for servers

  tasks:
    # For important (i.e. security-related) tasks that should be done early
    - name: Early server setup
      block:
        - name: Set hostname
          ansible.builtin.hostname:
            name: "{{ inventory_hostname }}"

        - name: Configure matthew user
          ansible.builtin.user:
            name: matthew
            comment: Matthew
            group: matthew
            groups:
              - matthew
              - sudo
            home: /home/matthew
            password: "{{ password_hash }}"
            password_lock: false
            shell: /bin/bash

        - name: Configure SSH
          ansible.builtin.template:
            src: ./config-files/sshd_config.j2
            dest: /etc/ssh/sshd_config
            owner: root
            group: root
            mode: u=rw,g=r,o=r
          notify:
            - Reload SSH

        - name: Apply SSH configuration changes immediately
          ansible.builtin.meta: flush_handlers

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

        - name: Install required packages
          ansible.builtin.apt:
            name:
              - ufw
              - fail2ban
              - unattended-upgrades
            state: present

        - name: Create UFW allow rules
          community.general.ufw:
            rule: allow
            direction: in
            proto: "{{ item.proto }}"
            to_port: "{{ item.port }}"
            comment: Allow {{ item.name }}
          loop:
            - {name: SSH, proto: tcp, port: "{{ ansible_port }}"}
            - {name: HTTP, proto: tcp, port: 80}
            - {name: HTTPS, proto: tcp, port: 443}
          register: ufw_create

        - name: Delete old UFW rules
          community.general.ufw:
            delete: true
            rule: allow
            direction: in
            proto: "{{ item.proto }}"
            to_port: "{{ item.port }}"
          loop:
            - {name: WireGuard, proto: udp, port: 51820}
          vars: {} # Deliberately empty block due to formatter bug: https://github.com/google/yamlfmt/issues/110

        - name: Enable UFW with default-deny policy
          community.general.ufw:
            default: deny
            state: enabled
          register: ufw_status

          # Important because removing a rule from the list of allow rules does not ensure that it is deleted
        - name: Fail if there are an unexpected number of UFW rules
          vars:
            rule_count: "{{ ufw_status.msg | split('\n') | select('search', ' (ALLOW|DENY|REJECT|LIMIT) ') | length }}"
            expected_rule_count: "{{ (ufw_create.results | length) * 2 }}"
          ansible.builtin.assert:
            that: rule_count == expected_rule_count
            fail_msg: |
              Unexpected number of UFW rules: expected {{ expected_rule_count }}, got {{ rule_count }}

              {{ ufw_status.msg }}

        - name: Configure fail2ban
          ansible.builtin.copy:
            src: ./config-files/{{ item }}
            dest: /etc/fail2ban/{{ item }}
            owner: root
            group: root
            mode: u=rw,g=r,o=r
          loop:
            - fail2ban.local
            - jail.local
          notify:
            - Reload fail2ban

        # https://wiki.debian.org/PeriodicUpdates
        - name: Configure unattended-upgrades
          ansible.builtin.copy:
            src: ./config-files/unattended-upgrades
            dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
            owner: root
            group: root
            mode: u=rw,g=r,o=r

        - name: Start and enable services
          ansible.builtin.service:
            name: "{{ item }}"
            state: started
            enabled: true
          loop:
            - ssh.service
            - ufw.service
            - fail2ban.service
            # For unattended-upgrades
            - apt-daily.timer
            - apt-daily-upgrade.timer

        - name: Ensure SSH socket activation is disabled
          ansible.builtin.service:
            name: ssh.socket
            state: stopped
            enabled: false

    - name: Upgrade apt packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full

    - name: Get package facts
      ansible.builtin.package_facts:
      no_log: true # Just to avoid long verbose output

    - name: Get latest Headscale release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/juanfont/headscale/releases/latest"
      register: headscale_version

    - name: Set Headscale-related facts
      ansible.builtin.set_fact:
        installed_headscale_version: "{{ ansible_facts.packages.headscale[0].version | default(None) }}"
        latest_headscale_version: "{{ headscale_version.json.tag_name[1:] }}"

    - name: Install or update Headscale
      when: installed_headscale_version != latest_headscale_version
      block:
        - name: Warn before installing an update
          when: installed_headscale_version is not none
          ansible.builtin.pause:
            prompt: |
              Headscale will be updated from v{{ installed_headscale_version }} to v{{ latest_headscale_version }}!

              Remember to read the release notes at https://github.com/juanfont/headscale/releases/tag/v{{ latest_headscale_version }} and check for breaking changes.

              Press enter to continue.

        - name: Stop Headscale
          when: installed_headscale_version is not none
          ansible.builtin.service:
            name: headscale
            state: stopped

        - name: Check if Headscale database files exist
          ansible.builtin.stat:
            path: /var/lib/headscale/{{ item }}
            get_checksum: false
          loop:
            - db.sqlite
            - db.sqlite-wal
            - db.sqlite-shm
          register: headscale_database

        - name: Back up Headscale database files
          ansible.builtin.fetch:
            src: "{{ item.stat.path }}"
            dest: ./backups/headscale-update-to-v{{ latest_headscale_version }}/
          loop: "{{ headscale_database.results }}"
          when: item.stat.exists

        - name: Download Headscale package
          vars:
            architecture: "{{ (ansible_facts.architecture == 'x86_64') | ternary('amd64', (ansible_facts.architecture == 'aarch64') | ternary('arm64', notdefined)) | mandatory(msg='Unsupported Headscale architecture: ' + ansible_facts.architecture) }}"
          ansible.builtin.get_url:
            url: https://github.com/juanfont/headscale/releases/download/v{{ latest_headscale_version }}/headscale_{{ latest_headscale_version }}_linux_{{ architecture }}.deb
            force: true
            dest: /tmp/headscale.deb

        - name: Install Headscale package
          ansible.builtin.apt:
            deb: /tmp/headscale.deb
            state: present

        - name: Delete Headscale package
          ansible.builtin.file:
            path: /tmp/headscale.deb
            state: absent

    - name: Configure Headscale
      ansible.builtin.template:
        src: ./config-files/headscale-config.yaml.j2
        dest: /etc/headscale/config.yaml
        owner: root
        group: headscale
        mode: u=rw,g=r,o=
      notify:
        - Reload Headscale

    - name: Configure Headscale ACLs
      ansible.builtin.copy:
        src: ./config-files/headscale-acl.json
        dest: /etc/headscale/acl.json
        owner: root
        group: headscale
        mode: u=rw,g=r,o=
      notify:
        - Reload Headscale

    - name: Start and enable Headscale service
      ansible.builtin.service:
        name: headscale
        state: started
        enabled: true

    # Instructions from https://pkgs.tailscale.com/stable/
    - name: Install Tailscale
      block:
        - name: Create keyrings directory
          ansible.builtin.file:
            dest: /usr/share/keyrings
            state: directory
            owner: root
            group: root
            mode: u=rwx,g=rx,o=rx

        - name: Add Tailscale's GPG key
          ansible.builtin.get_url:
            url: https://pkgs.tailscale.com/stable/debian/{{ ansible_facts.distribution_release }}.noarmor.gpg
            force: true
            dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
            owner: root
            group: root
            mode: u=rw,g=r,o=r

        - name: Add Tailscale repository
          ansible.builtin.get_url:
            url: https://pkgs.tailscale.com/stable/debian/{{ ansible_facts.distribution_release }}.tailscale-keyring.list
            force: true
            dest: /etc/apt/sources.list.d/tailscale.list
            owner: root
            group: root
            mode: u=rw,g=r,o=r

        - name: Install Tailscale package
          ansible.builtin.apt:
            update_cache: true
            name:
              - tailscale
              # Isn't strictly necessary, but it seems cleaner to have the key owned by a package
              - tailscale-archive-keyring
            state: present

        - name: Start and enable tailscaled
          ansible.builtin.service:
            name: tailscaled
            state: started
            enabled: true

    - name: Get Headscale users
      ansible.builtin.command:
        cmd: headscale users list --output json
      changed_when: false
      register: raw_current_headscale_users

    - name: Parse Headscale users
      ansible.builtin.set_fact:
        current_headscale_users: "{{ raw_current_headscale_users.stdout | from_json }}"

    - name: Create Headscale users
      loop: "{{ headscale_users }}"
      when: item not in (current_headscale_users | map(attribute='name'))
      ansible.builtin.command:
        cmd: headscale users create "{{ item }}"

    - name: Delete extraneous Headscale users
      loop: "{{ current_headscale_users | map(attribute='name') }}"
      when: item not in headscale_users
      ansible.builtin.command:
        cmd: headscale users delete --name "{{ item }}" --force

  handlers:
    - name: Test SSH configuration
      listen:
        - Reload SSH
      ansible.builtin.command:
        cmd: sshd -T
      changed_when: false

    - name: Reload SSH service
      listen:
        - Reload SSH
      ansible.builtin.service:
        name: ssh
        state: reloaded

    - name: Test fail2ban configuration
      listen:
        - Reload fail2ban
      ansible.builtin.command:
        cmd: fail2ban-client --test
      changed_when: false

    - name: Reload fail2ban service
      listen:
        - Reload fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: reloaded

    - name: Test Headscale configuration
      listen:
        - Reload Headscale
      ansible.builtin.command:
        cmd: headscale configtest
      changed_when: false

    - name: Restart Headscale service
      # Note: a full restart is required to handle changes in bind addresses
      listen:
        - Reload Headscale
      ansible.builtin.service:
        name: headscale
        state: restarted
