- name: Server setup
  hosts: gateway
  become: true
  vars:

  tasks:
    - name: Early server setup
      ansible.builtin.import_role:
        name: server_setup

    - name: Upgrade apt packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full

    - name: Set up Headscale
      ansible.builtin.import_role:
        name: headscale

    - name: Set up and connect Tailscale to Headscale
      ansible.builtin.import_role:
        name: tailscale
