- name: First-boot users and SSH server setup
  hosts: hetz-de

  tasks:
   - name: Create matthew user
     ansible.builtin.user:
      name: matthew
      append: true
      groups: sudo

- name: Server setup
  hosts: hetz-de

  tasks:
   - name: Update apt packages
     ansible.builtin.apt:
      update_cache: true
      upgrade: full
